# Generated by Django 5.2.8 on 2025-11-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='category',
            field=models.CharField(choices=[('regular', 'Regular Contribution'), ('social', 'Social Contribution'), ('lateness_fee', 'Lateness Fee')], default='regular', max_length=20),
        ),
    ]
