# Generated by Django 5.1.7 on 2025-11-05 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='gallery/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional thumbnail for videos', null=True, upload_to='gallery/thumbnails/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
                'ordering': ['order', '-uploaded_at'],
                'indexes': [models.Index(fields=['-uploaded_at', 'media_type'], name='gallery_med_uploade_c8e454_idx'), models.Index(fields=['is_active', 'order'], name='gallery_med_is_acti_1e9ee3_idx')],
            },
        ),
    ]
